Split makefile into GDSLVS and LVS

diff --git a/mag/Makefile b/mag/Makefile
--- a/mag/Makefile
+++ b/mag/Makefile
@@ -2,16 +2,10 @@ PROJECT_NAME ?= tt_um_baal86_openschnapp
 MAGIC_RC := $(PDK_ROOT)/gf180mcuD/libs.tech/magic/gf180mcuD.magicrc
 TEMPLATE_FILE := tt_analog_1x2.def
 
-.PHONY: lvs magic start
+.PHONY: gdslvs lvs magic start
 
 magic:
 	magic -rcfile $(MAGIC_RC) $(PROJECT_NAME).mag
-
-tt_analog_1x2.def:
-	wget https://raw.githubusercontent.com/TinyTapeout/tt-support-tools/tt08/def/analog/tt_analog_1x2.def
-
-tt_analog_1x2_3v3.def:
-	wget https://raw.githubusercontent.com/TinyTapeout/tt-support-tools/tt08/def/analog/tt_analog_1x2_3v3.def
 
 start: $(TEMPLATE_FILE)
 	magic -rcfile $(MAGIC_RC) -noconsole -dnull tcl/tt-analog-draw.tcl $(TEMPLATE_FILE) $(PROJECT_NAME)
@@ -20,6 +14,10 @@ parax: clean $(PROJECT_NAME).sim.spice
 
 $(PROJECT_NAME).lvs.spice: $(PROJECT_NAME).mag
 	magic -rcfile $(MAGIC_RC) -noconsole -dnull tcl/extract_for_lvs.tcl $(PROJECT_NAME)
+	rm -f *.ext
+
+$(PROJECT_NAME).gdslvs.spice: $(PROJECT_NAME).mag
+	magic -rcfile $(MAGIC_RC) -noconsole -dnull tcl/extract_for_gdslvs.tcl $(PROJECT_NAME)
 	rm -f *.ext
 
 antenna:
@@ -35,6 +33,9 @@ $(PROJECT_NAME).sim.spice: $(PROJECT_NAME).mag
 
 lvs.report: $(PROJECT_NAME).lvs.spice ../src/project.v
 	netgen -batch eval "set project $(PROJECT_NAME) ; source tcl/lvs_netgen.tcl"
+
+gdslvs.report: $(PROJECT_NAME).gdslvs.spice ../src/project.v
+	netgen -batch eval "set project $(PROJECT_NAME) ; source tcl/gdslvs_netgen.tcl"
 
 lvs: lvs.report
 	@propOk=1; match=0; port=1; \
@@ -64,9 +65,37 @@ lvs: lvs.report
 	    exit 1; \
     fi
 
+gdslvs: gdslvs.report
+	@propOk=1; match=0; port=1; \
+    if grep -q "match uniquely" gdslvs.report; then \
+        match=1; \
+    fi; \
+    if grep -q "Property errors were found" gdslvs.report; then \
+        propOk=0; \
+    fi; \
+    if grep -q "failed pin matching" gdslvs.report; then \
+        match=0; \
+    fi; \
+    if grep -q "Final result: Netlists do not match" gdslvs.report; then \
+        match=0; \
+    fi; \
+    if grep -q "port errors" gdslvs.report; then \
+        port=0; \
+    fi; \
+    if grep -q "Final result: Circuits match uniquely\." gdslvs.report; then \
+        match=1; \
+    fi; \
+	if [ $$match -eq 1 ] && [ $$propOk -eq 1 ] && [ $$port -eq 1 ]; then \
+        echo "GDS LVS OK"; \
+	    exit 0; \
+    else \
+        echo "GDS LVS FAIL: match=$$match properties=$$propOk port=$$port"; \
+	    exit 1; \
+    fi
+
 update_gds:
 	mkdir -p ../gds ../lef
 	magic -rcfile $(MAGIC_RC) -noconsole -dnull tcl/update_gds_lef.tcl $(PROJECT_NAME)
 
 clean:
-	rm -f lvs.report *.lvs.spice *.nodes
+	rm -f lvs.report gdslvs.report *.lvs.spice *.gdslvs.spice *.nodes
